name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Rebuild sqlite3
        run: npm rebuild sqlite3

      - name: Set execute permissions for Jest
        run: npm i -g jest

      - name: Run unit tests
        run: npm test

     

      - name: Run Performance Tests
        run: npm run performance

      - name: Audit Dependencies
        run: npm run dependency_audit

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress E2E tests
        run: npm run e2e
